name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: List files in directory
        run: ls -l ./node_modules/.bin

      - name: Set permissions for wdio
        run: chmod +x ./node_modules/.bin/wdio

      - name: Running E2E tests
        run: npx wdio run ./wdio.conf.ts --spec ./test/specs/makemytrip/*.ts

      - name: Generate Allure report
        run: npx allure generate --clean

      - name: Publish Allure report
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: allure-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
